[Paths]


[LOGGING]
log_retention_days = 7
log_directory = logs
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = project

[WHISPER]
MODEL = whisper-large-v3
LANGUAGE = ja
PROMPT =